defaults:
  - dataset: lingo
  - guidance:
      - pelvis
  - model:
      - synhsi_body
  - sampler:
      - pelvis
  - _self_

exp_name: train5.28
train: true
load_state_dict: false
batch_size: 8
lr: 0.0001
epochs: 300
device: cuda:0
ckpt_name: None
use_tensorboard: true
use_wandb: true
wandb_project: HSI-ours
wandb_entity: null
wandb_run_name: ${exp_name}
wandb_mode: online
log_interval: 10
ckpt_interval: 50
use_validation: true
val_split: val
val_interval: 1
val_batch_size: ${batch_size}

exp_dir: ${oc.env:ROOT_DIR}/results/${exp_name}
smpl_dir: ${oc.env:ROOT_DIR}/smpl_models

num_gpus: 7
num_workers: 8
scene_type: occ_two
max_window_size: 120
motion_len: 100000
vis: false
start_type: stand

load_language: true
load_scene: true
use_pi: true
load_hand_goal: true
load_pelvis_goal: true
load_object: false
auto_regre_num: 2

dataset:
  split: train

ckpt_path: None

hydra:
  run:
    dir: ${exp_dir}
