pelvis:
  _target_: models.synhsi.Sampler
  device: ${device}
  mask_ind: ${guidance.pelvis.mask_ind}
  emb_f: ${guidance.pelvis.emb_f}
  batch_size: ${batch_size}
  channel: ${times:${dataset.nb_joints},3}
  auto_regre_num: ${auto_regre_num}
  use_motion_state: ${use_motion_state}
  motion_state_len: ${motion_state_len}
  timesteps: 50
  objective: flow_matching
  beta_schedule: linear
  beta_schedule_s: 0.008
  beta_start: 0.0001
  beta_end: 0.02
  clip_denoised: false
  clip_denoised_min: -1.5
  clip_denoised_max: 1.5
  debug_sampling: false
  motion_len: ${motion_len}
  scene_type: ${scene_type}
  use_aux_losses: ${use_aux_losses}
  completion_pos_weight: ${completion_pos_weight}
  aux_loss_weights: ${aux_loss_weights}
